### ISSUE TITLE
Curiosity -- What Attributes on DTO and not service objects

### ISSUE THREAD

**Issue by ravensorb** [pete-restall/Nancy.ServiceRouting#1]
I am been looking at this module and I am trying to wrap my head around using the HTTP verbs on objects rather than on operations.  What I am having the hardest time is -- how do I use the same DTO for several types of actions especially when I might have more than one "service" within my endpoint.

**Comment by pete-restall** [comment]
Thanks for the comment - and sorry for the delay in replying.

By 'Operations', I'm assuming you're looking at this from a WCF point of view.  WCF is indeed more of an Operation-based framework rather than a Message-based framework.  The trouble with those is that they tend to be 'chatty' and encourage calling remote methods as if they were local methods, which has serious performance and scalability implications.  Obviously WCF can be made hugely scalable, but you need to add a little though (like anything...)

The idea in Nancy.ServiceRouting is to use the DTOs in the construction of Message-Based Services, so you'd use one DTO per Service End-Point.  This is pretty much how ServiceStack does it, too, which was really the inspiration for making this Nancy plugin.  There's nothing stopping you from modifying the conventions, though - ie. several different NancyModules that register different Service types via the RouteRegistrar, possibly with different base URIs for example.

While there is one main 'Request' type of DTO per Service End-Point, in a reasonably complex system these will probably be composites of smaller, shared DTOs that will not be dispatchable to Service End-Points on their own as it wouldn't make sense.  Nancy's ModelBinder should help here.

Putting the attributes on the DTOs rather than the Service End-Points allows you to see the mappings between URI parts in the Route Templates and the properties in the DTOs.  It also makes a bit more logical sense, as the URI is really part of the Request - the Service shouldn't care about where it's hosted as long as it gets the data it needs (ie. the DTO); it may not even be over HTTP (think of 'Service' in a DDD way, for example).

The DTOs are Messages, which are the core of this paradigm; the Services just happen to be able to act on those Messages, whatever delivery mechanism is in place.  Again, this is how ServiceStack does it - they actually support Message Buses for delivery, too.

I hope this helps.
